CREATE DATABASE prova;
USE prova;

CREATE TABLE usuario (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nome VARCHAR(100) NOT NULL,
  email VARCHAR(150) NOT NULL UNIQUE,
  senha VARCHAR(64) NOT NULL
);

CREATE TABLE sala (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nome VARCHAR(150) NOT NULL,
  criador_id INT NOT NULL,
  FOREIGN KEY (criador_id) REFERENCES usuario(id) ON DELETE CASCADE
);

CREATE TABLE salaPermissao (
  id INT AUTO_INCREMENT PRIMARY KEY,
  sala_id INT NOT NULL,
  usuario_id INT NOT NULL,
  aprovado BOOLEAN DEFAULT FALSE,
  FOREIGN KEY (sala_id) REFERENCES sala(id) ON DELETE CASCADE,
  FOREIGN KEY (usuario_id) REFERENCES usuario(id) ON DELETE CASCADE,
  UNIQUE (sala_id, usuario_id)
);

CREATE TABLE chat (
  id INT AUTO_INCREMENT PRIMARY KEY,
  usuario_id INT NOT NULL,
  sala_id INT NOT NULL,
  mensagem TEXT NOT NULL,
  criacao DATETIME DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (usuario_id) REFERENCES usuario(id) ON DELETE CASCADE,
  FOREIGN KEY (sala_id) REFERENCES sala(id) ON DELETE CASCADE
);
